### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by pythonanonuser** [chili-epfl/attention-tracker#1]
Hi,

I was just testing out this library for a project on Mac OSX 10.9. When trying to make the examples after running cmake I was getting the following error associated with the file head_pose_estimation.hpp:

error: no type named 'shape_predictor' in namespace 'dlib'
    dlib::shape_predictor pose_model;

I have the shape predictor file for dlib to detect the landmarks. Just a bit confused as how to proceed. Any advice?

Thanks!

**Comment by severin-lemaignan** [comment]
Thanks for trying out!
This error comes from a small API change between `dlib-18.16` and `dlib-18.17`.

Since `dlib` does not provide any easy way to get its version number, I did not fix the issue in a proper way yet.

In the meantime, just add:

``` c++
#include <dlib/image_processing.h>
```

near the top of `head_pose_estimation.hpp`, and this should solve you issue.
To fix it, you need

**Comment by severin-lemaignan** [comment]
Note that `dlib` has another issue related to position independent code: to successfully link (anything) to `dlib`, you also need to modify **dlib's** `CMakeLists` (found in `$DLIB_ROOT/dlib/CMakelists.txt`) and add `add_definitions(-fPIC)` near the top (around line 20).

**Comment by 12rohanb** [comment]
Thanks for the tip, it worked, but I'm having some more issues compiling the provided programs.

I'm using g++ and trying to compile the program head_pose_estimation_test.cpp and getting the following error

Undefined symbols for architecture x86_64:
  "_USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_", referenced from:
      _dlib_check_consistent_assert_usage in head_pose_estimation_test-07450f.o
  "HeadPoseEstimation::poses()", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "HeadPoseEstimation::update(cv::Mat)", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "HeadPoseEstimation::HeadPoseEstimation(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float)", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "cv::namedWindow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "cv::VideoCapture::set(int, double)", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "cv::VideoCapture::VideoCapture(int)", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "cv::VideoCapture::~VideoCapture()", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "cv::VideoCapture::operator>>(cv::Mat&)", referenced from:
      _main in head_pose_estimation_test-07450f.o
  "cv::Mat::deallocate()", referenced from:
      cv::Mat::release() in head_pose_estimation_test-07450f.o
  "cv::Mat::copySize(cv::Mat const&)", referenced from:
      cv::Mat::Mat(cv::Mat const&) in head_pose_estimation_test-07450f.o
  "cv::fastFree(void*)", referenced from:
      cv::Mat::~Mat() in head_pose_estimation_test-07450f.o
  "cv::VideoCapture::isOpened() const", referenced from:
      _main in head_pose_estimation_test-07450f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you please advise? Or should I be testing out the library in a different manner?

**Comment by 12rohanb** [comment]
Thanks for the tip. I'm having some trouble compiling the sample program that you've provided, head_pose_estimation_test.cpp

I've linked all the opencv libraries successfully but am still receiving the following error

Undefined symbols for architecture x86_64:
  "cv::namedWindow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      _main in head_pose_estimation_test-7f7a91.o
  "cv::VideoCapture::set(int, double)", referenced from:
      _main in head_pose_estimation_test-7f7a91.o
  "cv::VideoCapture::VideoCapture(int)", referenced from:
      _main in head_pose_estimation_test-7f7a91.o
  "cv::VideoCapture::~VideoCapture()", referenced from:
      _main in head_pose_estimation_test-7f7a91.o
  "cv::VideoCapture::operator>>(cv::Mat&)", referenced from:
      _main in head_pose_estimation_test-7f7a91.o
  "cv::VideoCapture::isOpened() const", referenced from:
      _main in head_pose_estimation_test-7f7a91.o
ld: symbol(s) not found for architecture x86_64

Can you please advise on what might be the best route to compile some of the programs you've given?

**Comment by severin-lemaignan** [comment]
@12rohanb Does it work for you now? can I close the issue?

**Comment by pythonanonuser** [comment]
Sorry for the delay. I was having some trouble compiling earlier, but everything's working great now. Thanks for the advice.

**Comment by severin-lemaignan** [comment]
Fine, closing the issue.
