### ISSUE TITLE
Installing the Library

### ISSUE THREAD

**Issue by walidkalash** [chili-epfl/attention-tracker#26]
I was able to compile the sample files perfectly but I wasn't able to install the library to include it in another project.

I didn't know where to run "make install" exactly. I tried it in several places but with no luck. I am getting the following error: make: *** No rule to make target 'install'. Stop.

So how should I install it and how do I include it exactly?

Thanks in advance.

**Comment by severin-lemaignan** [comment]
The typical usage (standard cmake workflow) would be:
```
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make install
```
You can pass options to `cmake` to configure where libraries should be installed.
