### ISSUE TITLE
Other pnp methods and more landmarks?

### ISSUE THREAD

**Issue by jormansa** [chili-epfl/attention-tracker#9]
Thanks for sharing the code, it is really great. A couple of questions. ¿Have you tried other pnp methods implemented in opencv 3 (EPNP, P3P, DLS, UPNP)? ¿Have your tried a different number of landmarks? Thanks.

**Comment by severin-lemaignan** [comment]
Hello, and thank you for your interest.

While I do not remember precisely, I believe I've tried the whole range of PnP solver and eventually found the default iterative one to work best. But if you experiment again (ideally, with an existing dataset), please let us know your results.

The number of landmark is constrained by what dlib provide by default: while we could train our own faces model with more landmarks (dlib provides a tool for that), we did not feel it was necessary as the default model is already working really well.

**Comment by jormansa** [comment]
Thank for the fast reply. About using a different number of landmarks, I meant to say to use more 3D head model landmarks (even 68) to estimate a more robust trasnformation. Obviously, you need to manually label those landmarks in the model. Anyway, with the actual 9 landmarks works really well and probably there will be no much difference. Thanks again.

**Comment by severin-lemaignan** [comment]
I did try to track more landmarks for the 3D reconstruction (if I remember correctly, up to 14), without any obvious improvement of robustness/stability.
